# Transcription of "1. Size zero combined styles.pdf" (52 pages = 52 styles).
# Swatch hex values are sampled from the PDF itself (tools/swatches.json), in reading order.
# name, category are descriptive (the catalogue only has style codes); price/mrp are PLACEHOLDERS (INR).

F1 = "82.5% Polyester, 17.5% Elastane"
M94 = ("Mesh", "94% Polyester, 6% Elastane")
LN = ("Lining", "94.5% Polyester, 5.5% Elastane")
S_XXL = ["S", "M", "L", "XL", "XXL"]
S_XXXL = S_XXL + ["XXXL"]
XS_XXL = ["XS"] + S_XXL

# (page, code, name, category, composition, extras, sizes, [colour names], price, mrp, blurb)
P = [
 (1,"JYJN050","Cross-Back Support Sports Bra","Sports Bras","80% Nylon, 20% Elastane",[],S_XXL,
  ["Aima Blue","Niuzai Blue","Black","Qianniu Purple","Dark Red","Sun Grey","Coffee","Dark Plum Purple","Yunshi Grey","Light Milky White"],1199,1599,
  "Wide scoop neckline with a criss-cross back and panelled front for a secure, flattering fit."),
 (2,"JYBMN0006","Contrast-Piping Racerback Sports Bra","Sports Bras",F1,[M94],S_XXL,
  ["Black","White","Coffee","Grey"],1099,1499,"Racerback bra with fine contrast piping and a mesh panel. Pairs with the matching piped leggings."),
 (3,"JYBMN0008","Banded Racerback Sports Bra","Sports Bras",F1,[M94],S_XXL,
  ["Black","White","Coffee","Pink"],1099,1499,"Scoop-neck racerback bra with a soft striped elastic band and mesh detail."),
 (4,"JYJN021","Strappy-Back Yoga Bra","Sports Bras","78% Nylon, 22% Elastane",[],S_XXL,
  ["Black","Cream","Desert Sunlight"],999,1399,"Light, smooth yoga bra with delicate Y-straps across the back."),
 (5,"JYJN035","Keyhole-Back Sports Bra","Sports Bras","78% Nylon, 22% Elastane",[],S_XXL,
  ["Black","Cream","Desert Sunlight"],1099,1499,"Racer-style bra with a keyhole cut-out and perforated back panel for airflow."),
 (6,"JYJN054","Twist-Front Halter Top","Tops & Tees","80% Nylon, 20% Elastane",[],S_XXL,
  ["Dark Red","Niuzai Blue","Qianniu Purple","Dark Plum Purple","Black"],999,1399,"V-neck halter crop top with a twist knot at the hem. Court-to-cafe ready."),
 (7,"JYJN067","Mesh Cut-Out Back Sports Bra","Sports Bras","80% Nylon, 20% Elastane",[M94],S_XXL,
  ["Qianniu Purple","Yunshi Grey","Black","Coffee"],1199,1599,"Strappy back with a breathable mesh cut-out. Stays put through every move."),
 (8,"JYMB008","Relaxed Curved-Hem Tank","Tops & Tees","88% Polyester, 12% Elastane",[],S_XXL,
  ["Purple","Green","Black"],799,1199,"Easy, flowing sleeveless tank with a curved hem. Layers over a bra or wear on its own."),
 (9,"JYMB062","Printed Mesh Cami Top","Tops & Tees",F1,[M94],S_XXL,
  ["Milky White","Sea Green","Light Pink","Black","Light Purple"],899,1299,"Cami top with a printed mesh overlay and ruched front. A pretty studio-to-street piece."),
 (10,"JYMB144","Cross-Tie Back Sports Bra","Sports Bras",F1,[],S_XXL,
  ["Black","Pale Aqua Blue","Rouwu Pink","Grey"],1099,1499,"Soft bra with a criss-cross tie back and a clean scoop neckline."),
 (11,"JYMB164","Slim Strappy Tank","Tops & Tees",F1,[],S_XXL,
  ["Milky White","Black","Rouwu Pink","Apple Green"],799,1199,"Slim-fit tank with adjustable-look straps. Light, stretchy and easy to style."),
 (12,"JYMD011","Short-Sleeve Crop Top","Tops & Tees",F1,[],S_XXL,
  ["Matcha","Magenta","Black","Light Pink"],899,1299,"Short-sleeve cropped top with a soft scoop neck and slim fit."),
 (13,"JYMD012","Cut-Out Neckline Short-Sleeve Top","Tops & Tees",F1,[],S_XXL,
  ["Milky White","Blue","Black","Light Pink","Matcha"],949,1349,"Short-sleeve cropped top with a statement asymmetric cut-out neckline."),
 (14,"JYMN005","Square-Neck Crop Tank","Tops & Tees",F1,[],S_XXXL,
  ["Blue","Milky White","Black","Matcha","Dark Blue","Dusty Rose","Magenta","Bright Yellow","Pink","Dark Purple","Light Pink","Medium Purple","Dark Brown","Coffee","Reddish Orange"],999,1399,
  "Wide-strap square-neck crop tank with panelled seams. Available in 15 colours and up to XXXL."),
 (15,"JYMN153","Wide-Strap Crop Bra Top","Sports Bras",F1,[],S_XXL,
  ["White","Sea Green","Royal Blue","Black"],1099,1499,"Supportive wide-strap crop top with a square neckline and structured band."),
 (16,"JYMN187","Longline Square-Neck Bra","Sports Bras",F1,[],S_XXL,
  ["Dark Green","Light Grey","Green","Black","Magenta","Reddish Orange"],1099,1499,"Longline bra with a square neck, wide straps and a smooth silhouette."),
 (17,"JYMN236","Cross-Strap Back Tank","Tops & Tees",F1,[],S_XXL,
  ["White","Ice Melt Blue","Rouwu Pink","Grey","Black"],899,1299,"Tank with crossed straps and ruched back detail. Pairs perfectly with a skort."),
 (18,"JYMN246","Open-Back Twist Tank","Tops & Tees",F1,[],S_XXL,
  ["White","Green","Khaki","Raspberry","Black"],899,1299,"Sleeveless top with a twisted open back. Bold on the court, studio or street."),
 (19,"JYTN011","Classic Racerback Sports Bra","Sports Bras",F1,[],S_XXL,
  ["Apricot","Coffee","Black","Orange"],999,1399,"A true everyday racerback bra in rich, wearable colours."),
 (20,"JYWB003","Loose-Fit Sleeveless Tank","Tops & Tees","88% Polyester, 12% Elastane",[],S_XXL,
  ["White","Light Pink","Muted Pink","Black","Pale Aqua Blue"],749,1099,"Relaxed, airy sleeveless tank with a rounded hem. Effortless over any bra."),
 (21,"MTWXW01","Mesh-Panel Sports Bra","Sports Bras",F1,[],S_XXL,
  ["Blue","Dark Blue","Black","Reddish Orange","Dusty Rose"],1099,1499,"Scoop-neck bra with mesh yoke and wide band for steady support."),
 (22,"MTXWX60","Mesh-Neck Bra Tank","Tops & Tees",F1,[],S_XXL,
  ["Blue","Dark Blue","Black","Dark Purple","Dusty Rose"],999,1399,"Longline tank with sheer mesh neckline and slim, panelled body."),
 (23,"OMMN019","Multi-Strap Back Sports Bra","Sports Bras","78% Polyester, 22% Elastane",[],["XS","S","M","L","XL"],
  ["Light Purple","Black","Ultra White"],1099,1499,"Show-off back with multiple fine straps. Medium-impact styling with a sleek front."),
 (24,"OMMN056","Piped Halter V-Neck Sports Bra","Sports Bras",F1,[M94],XS_XXL,
  ["Black","White","Pink","Coffee"],1199,1599,"Halter V-neck bra with contrast piping. Matches the Wrap Tennis Skirt for a full tennis look."),
 (25,"JYWC027","Sheer Lightweight Long-Sleeve Top","Long Sleeves & Jackets","100% Polyester",[],["M","L","XL"],
  ["Cloud White","Sheer Yellow","Sheer Pink","Sheer Blue"],1099,1499,"Airy, semi-sheer long-sleeve with side ruching. A breezy cover-up for sun and studio."),
 (26,"JYWC031","Half-Zip Long-Sleeve Top","Long Sleeves & Jackets","88% Polyester, 12% Elastane",[("Mesh","89% Polyester, 11% Elastane")],S_XXL,
  ["Muted Pink","Pale Aqua Blue","Grey","Black"],1399,1899,"Fitted half-zip pullover with thumbholes. Warm-up essential."),
 (27,"JYMW183","Contrast-Piping Zip Jacket","Long Sleeves & Jackets",F1,[],S_XXL,
  ["White","Black"],1799,2399,"Stand-collar zip-up jacket with sleek contrast piping. Matches the piped bra and leggings."),
 (28,"JYMW261","Slim-Fit Zip Jacket","Long Sleeves & Jackets",F1,[],S_XXXL,
  ["Black","White","Blue","Grey","Coffee","Plum Purple"],1799,2399,"Fitted zip jacket with thumbholes and a flattering waist. Six colours up to XXXL."),
 (29,"MTWT01","Stand-Collar Zip Jacket","Long Sleeves & Jackets",F1,[],S_XXXL,
  ["Raspberry Red","Dark Blue","Black","Grey","Dark Purple","Coffee","White","Blue","Light Pink","Matcha","Cocoa","Dazzling Sun","Dusty Rose","Milky White","Pink","Burgundy","Medium Purple","Reddish Orange","Ice Melt Blue","Plum Purple"],1899,2499,
  "Our widest colour range: 20 shades. Panelled zip jacket with a stand collar and thumbholes."),
 (30,"MTWTP02","Hooded Zip Jacket","Long Sleeves & Jackets",F1,[],S_XXL,
  ["Blue","Magenta","Black","Dark Blue"],1899,2499,"Hooded zip-up with a fitted shape and soft stretch. Pairs with matching shorts or leggings."),
 (31,"JYJD017","Fitted Crew-Neck Tee","Tops & Tees","80% Nylon, 20% Elastane",[],S_XXL,
  ["Black","White","Coffee","Sheer Yellow","Soft Tulle Pink","Aima Blue"],899,1299,"Slim crew-neck tee with short sleeves in smooth, stretchy fabric."),
 (32,"JYMD163","Open-Back Short-Sleeve Tee","Tops & Tees",F1,[],S_XXL,
  ["Black","Ice Melt Blue","Rouwu Pink","Cocoa"],999,1399,"Short-sleeve tee with a strappy open back and twist detail."),
 (33,"JYMD187","Polo Collar Tennis Tee","Tops & Tees",F1,[],S_XXL,
  ["Black","White","Rouwu Pink","Grey","Ice Melt Blue"],999,1399,"Fitted polo-collar tee with a V placket. Made for the court."),
 (34,"JYWD008","Oversized Side-Slit Tee","Tops & Tees","88% Polyester, 12% Elastane",[],S_XXL,
  ["White","Light Pink","Black","Light Blue"],799,1199,"Roomy, drop-shoulder tee with side slits and panel seams. Easy all-day comfort."),
 (35,"JYWD020","Slim Sports Tee","Tops & Tees","88% Polyester, 12% Elastane",[("Mesh","96.9% Polyester, 3.1% Elastane")],S_XXL,
  ["White","Light Pink","Black","Pale Aqua Blue"],849,1249,"Lightweight fitted tee with breathable mesh panelling for runs and tennis."),
 (36,"JYBMK0015","Piped Flare Leggings","Leggings & Pants",F1,[],S_XXXL,
  ["Black","White","Coffee","Grey"],1499,1999,"High-waist flare leggings with contrast side piping. A figure-flattering classic."),
 (37,"JYJK026","High-Waist Leggings","Leggings & Pants","80% Nylon, 20% Elastane",[],S_XXL,
  ["Aima Blue","Niuzai Blue","Black","Qianniu Purple","Dark Red","Sun Grey","Coffee","Dark Plum Purple","Yunshi Grey"],1299,1799,"Smooth, full-length high-waist leggings with a wide waistband. Nine shades."),
 (38,"JYMK228","Crossover Wide-Leg Pants","Leggings & Pants",F1,[],S_XXL,
  ["Linghua White","Coffee","Black","Grey","Ice Blue","Rouwu Pink","Olive Green"],1599,2199,"Soft stretch wide-leg pants with a crossover high waist and curved seams."),
 (39,"JYMK310","Relaxed Wide-Leg Pants","Leggings & Pants",F1,[],S_XXL,
  ["Linghua White","Coffee","Black","Grey","Ice Blue","Rouwu Pink"],1599,2199,"Flowing wide-leg pants with a high waist. Studio to street."),
 (40,"JYWK025","Elastic-Hem Jogger Pants","Leggings & Pants","94% Polyester, 6% Elastane",[],S_XXL,
  ["Black","Dark Purple","Dark Grey"],1499,1999,"Relaxed joggers with an elasticated waist and ankle cuffs."),
 (41,"MT20","Ankle-Length Leggings","Leggings & Pants",F1,[],S_XXXL,
  ["Raspberry Red","Dark Blue","Black","Grey","Dark Purple","Coffee","Dark Grey","Blue","Magenta","Green","Cocoa","Khaki","Dusty Rose","Milky White","Reddish Orange","Olive Green","Medium Purple","Burgundy","Plum Purple"],1299,1799,
  "High-rise leggings in 19 colours and sizes up to XXXL."),
 (42,"MTCK90","Side-Pocket Leggings","Leggings & Pants",F1,[],S_XXXL,
  ["Dark Grey","Dark Purple","Black","Dark Blue","Magenta","Blue","Coffee","Grey","Dusty Rose","Burgundy","Reddish Orange"],1399,1899,"High-waist leggings with a handy side pocket. 11 colours up to XXXL."),
 (43,"JYMA162","Contrast-Trim Sports Shorts","Shorts",F1,[],S_XXL,
  ["Black","Pale Aqua Blue","Coffee","Grey"],799,1199,"Short, snug shorts with a contrast waistband and curved hem."),
 (44,"JYMQ101","Wrap-Front Tennis Skort","Skirts & Skorts",F1,[],S_XXL,
  ["Black","White","Beke Pink","Cocoa"],1199,1599,"Twist-wrap skort with built-in shorts. Light, flirty and secure."),
 (45,"OMMQ033","Wrap Tennis Skirt","Skirts & Skorts",F1,[LN],XS_XXL,
  ["Black","White","Pink","Coffee"],1299,1699,"Asymmetric wrap skirt with a striped waistband and built-in lining shorts."),
 (46,"JYBSQ0004","Pleated Tennis Skirt","Skirts & Skorts","94% Polyester, 6% Elastane",[LN],S_XXL,
  ["Black","White","Coffee","Pink"],1299,1699,"Fully pleated skirt with an elastic waist and lined shorts underneath."),
 (47,"JYJQ001","Pleated Mini Skort","Skirts & Skorts","78% Nylon, 22% Elastane",[],["M","L","XL","XXL"],
  ["Black","Pink","White"],1199,1599,"Soft pleated mini with a smooth high waist. Move freely."),
 (48,"JYMQ089","A-Line Sports Skort","Skirts & Skorts",F1,[LN],S_XXL,
  ["White","Ice Melt Blue","Rouwu Pink","Grey","Black"],1199,1599,"Flared A-line skirt with built-in shorts and a flat high waistband."),
 (49,"JYTQ001","Flared Skort","Skirts & Skorts",F1,[],S_XXL,
  ["Apricot","Sea Green","Black","Coffee"],1199,1599,"Light, flared skort in soft, matte fabric. Great for tennis and walks."),
 (50,"MT5FK","Biker Shorts","Shorts",F1,[],S_XXL,
  ["Cocoa","Khaki","Blue","Dusty Rose","Grey","Dark Blue","Black","Dark Purple","Dark Grey","Raspberry Red","Light Milky White"],899,1299,"High-waist biker shorts that stay in place. 11 colours."),
 (51,"MT7FKDK","Cropped Capri Leggings","Leggings & Pants",F1,[],S_XXXL,
  ["Magenta","Burgundy","Blue","Dusty Rose","Grey","Dark Blue","Black","Dark Purple","Reddish Orange"],1199,1599,"Mid-length high-waist capri leggings with contoured seams."),
 (52,"MTSDK01","Running Shorts with Liner","Shorts","94% Polyester, 6% Elastane",[LN],S_XXL,
  ["Cocoa","Dark Blue","Black","Dark Purple","Grey"],999,1399,"Lightweight running shorts with a wide waistband, curved hem and inner lining."),
]
